# Generated by Django 4.2.7 on 2025-11-14 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_watch', '想看'), ('watching', '在看'), ('watched', '已看')], default='want_to_watch', max_length=20, verbose_name='状态')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('watched_at', models.DateTimeField(blank=True, null=True, verbose_name='观看时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='电影')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '观影清单',
                'verbose_name_plural': '观影清单',
                'db_table': 'watchlists_watchlist',
                'indexes': [models.Index(fields=['user', 'status', '-added_at'], name='watchlists__user_id_8f50e2_idx')],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
