# Generated by Django 4.2.7 on 2025-11-14 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie', 'score'], name='ratings_rat_movie_i_bff10a_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user', '-created_at'], name='ratings_rat_user_id_e6a510_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
    ]
