# Generated by Django 4.2.7 on 2025-11-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL友好名称')),
            ],
            options={
                'verbose_name': '电影类型',
                'verbose_name_plural': '电影类型',
                'db_table': 'movies_genre',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='豆瓣排名')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='电影名称')),
                ('original_title', models.CharField(blank=True, max_length=255, verbose_name='原始标题')),
                ('year', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='上映年份')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='国家/地区')),
                ('director', models.CharField(blank=True, max_length=255, verbose_name='导演')),
                ('cast', models.TextField(blank=True, verbose_name='主演')),
                ('genres', models.CharField(blank=True, max_length=100, verbose_name='类型')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='时长(分钟)')),
                ('summary', models.TextField(blank=True, verbose_name='剧情简介')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='海报图片')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='backdrops/', verbose_name='背景图片')),
                ('douban_url', models.URLField(blank=True, verbose_name='豆瓣链接')),
                ('douban_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='豆瓣评分')),
                ('avg_rating', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='本站平均评分')),
                ('rating_count', models.IntegerField(default=0, verbose_name='本站评分人数')),
                ('review_count', models.IntegerField(default=0, verbose_name='影评数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'db_table': 'movies_movie',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['douban_rating'], name='movies_movi_douban__c9e5a4_idx'), models.Index(fields=['avg_rating'], name='movies_movi_avg_rat_6515c7_idx'), models.Index(fields=['-created_at'], name='movies_movi_created_2750ad_idx')],
            },
        ),
    ]
